- name: Invoke Maven role
  ansible.builtin.include_role:
    name: common
    tasks_from: maven.yml

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load database schemas
  ansible.builtin.shell: mysql -h "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_HOST token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}" -uroot -p"{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/shipping:DB_USER token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}" < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data
    