- name: Copy rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    
- name: Install rabbitmq server version
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Enable and start app service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    enabled: true
    state: started

- name: Add user roboshop and set permissions
  ansible.builtin.shell: |
    rabbitmqctl add_user "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:USER_NAME token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}" "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/rabbitmq:PASSWORD token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"
    rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
