- name: Invoke Node JS role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yml

- name: Copy mongo repo servicefile
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Load Master Data
  ansible.builtin.shell: mongosh --host "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:MONGO_HOST token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}" </app/db/master-data.js
