- name: Download docker repo file
  ansible.builtin.get_utl:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/repos.d/docker-ce.repo

- name: Install docker
  ansible.builtin.dnf:
    name: docker-ce
    state: present

- name: Enable and start docker
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started
