- name: Install docker by invoking docker task
  ansible.builtin.include_role:
    name: common
    tasks_from: docker.yml

- name: Create a cart container
  community.docker.docker_container:
    name: cart
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    env:
      CATALOGUE_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/cart:CATALOGUE_HOST token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"
      CATALOGUE_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/cart:CATALOGUE_PORT token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"
      REDIS_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/cart:REDIS_HOST token={{ token }} url=http://vault.nareshdevops1218.online:8200') }}"
